extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
rules:
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  import/no-unresolved:
    - 1
  react/prop-types:
    - 1
env:
  browser: true
