exports.seed = function (knex, Promise) {
  return knex('blog_posts').del()
  .then(() => knex('blog_posts').insert([
    {
      id: 1,
      title: 'My First Blog Post!',
      content: 'Slow-carb meditation tattooed live-edge. Bicycle rights messenger bag wolf, +1 letterpress cardigan fingerstache next level literally shabby chic hashtag biodiesel hella mlkshk direct trade. Hoodie flannel direct trade ennui la croix fanny pack. Gluten-free live-edge whatever lumbersexual swag marfa migas umami kombucha thundercats deep v selfies. Organic ennui single-origin coffee kitsch. Meggings banjo succulents gastropub enamel pin freegan actually PBR&B hoodie yr. Glossier cardigan fingerstache, organic selvage occupy hammock kinfolk raclette kale chips disrupt microdosing. Taxidermy biodiesel pinterest tattooed cred small batch four dollar toast pok pok adaptogen succulents activated charcoal next level yr. Iceland echo park glossier kogi street art skateboard seitan mustache flannel etsy narwhal tacos. Dreamcatcher health goth banjo pitchfork heirloom put a bird on it.

      Pug cornhole leggings la croix activated charcoal ugh, scenester hammock. Tattooed venmo af banh mi flexitarian pitchfork freegan listicle enamel pin. Keytar occupy etsy pok pok, gluten-free offal readymade cloud bread 3 wolf moon drinking vinegar master cleanse. Freegan bespoke live-edge fam. Banh mi biodiesel shoreditch taiyaki flannel wayfarers. Gentrify deep v cloud bread heirloom normcore vexillologist beard godard post-ironic edison bulb poke pour-over butcher. Hot chicken austin stumptown, master cleanse mlkshk health goth everyday carry dreamcatcher bushwick. Hell of literally adaptogen ramps unicorn cornhole. Freegan jianbing cardigan ramps swag, meh flannel vice.

      Roof party direct trade mustache food truck synth. Fingerstache everyday carry ennui marfa pickled 3 wolf moon. Salvia drinking vinegar chambray hot chicken try-hard 90s organic gastropub shoreditch letterpress. Messenger bag offal ethical DIY church-key. Mixtape next level irony chambray. Cornhole echo park sustainable, chambray church-key butcher pinterest mixtape lyft. Lyft gluten-free synth street art pork belly. Direct trade lo-fi everyday carry, taxidermy cray letterpress mixtape hoodie pug deep v four loko cloud bread. Paleo bitters microdosing bushwick meggings plaid farm-to-table. Whatever vinyl bitters, heirloom locavore church-key cronut. Put a bird on it thundercats messenger bag bespoke letterpress gentrify stumptown kale chips venmo raw denim vice 90s. Tumblr snackwave bicycle rights chia. Freegan occupy health goth, poke chicharrones green juice la croix heirloom. Letterpress raw denim art party, mixtape occupy portland paleo lo-fi banjo PBR&B wolf seitan pug ennui hammock.

      Kitsch banjo hexagon four loko. Authentic affogato taxidermy bushwick pabst. Fam snackwave af meditation austin vegan. Godard roof party put a bird on it pug, echo park wolf pitchfork. Fingerstache food truck austin banjo. Keytar occupy meh messenger bag flannel chia actually lyft fanny pack portland fam affogato cornhole brunch next level. Raclette sriracha church-key, literally twee copper mug street art semiotics hexagon letterpress poutine banh mi. Chillwave +1 DIY, tumeric keytar vape cronut. Drinking vinegar meggings portland umami vinyl heirloom mustache activated charcoal fashion axe kitsch taiyaki ramps green juice. Readymade prism bitters poutine knausgaard, pork belly brunch sartorial umami vinyl drinking vinegar craft beer.

      Raclette cliche jianbing viral four loko. Leggings brooklyn chia hot chicken tumeric chicharrones palo santo hoodie trust fund vape. Kogi neutra pop-up, retro man bun tacos thundercats salvia kinfolk activated charcoal organic tofu drinking vinegar cornhole. Letterpress schlitz thundercats direct trade taxidermy, twee everyday carry migas meggings chicharrones lumbersexual farm-to-table sriracha hexagon chartreuse. You probably havent heard of them drinking vinegar master cleanse brunch, copper mug asymmetrical man braid. Prism locavore kitsch, cronut tofu sustainable sriracha actually cornhole deep v aesthetic tacos +1. Lyft umami stumptown, squid fam readymade single-origin coffee franzen microdosing yr flexitarian man bun fashion axe hell of. Fanny pack sriracha literally offal. Cray everyday carry hoodie disrupt cronut vegan tacos iPhone unicorn woke wolf glossier plaid health goth. XOXO intelligentsia succulents, hot chicken plaid twee knausgaard brooklyn YOLO. Selfies YOLO edison bulb sartorial, live-edge waistcoat af direct trade meh 3 wolf moon cronut fashion axe. Adaptogen green juice actually, vegan ugh fam health goth lo-fi chicharrones.',
      author: 1,
    },
  ]))
  .then(() => knex.raw('SELECT setval(\'blog_posts_id_seq\', (SELECT MAX(id) FROM blog_posts))'));
};
